## NumPy Libary
#### > It is the core libary for numerical & scientific computing in Python. It has multidimensional array as its data structures,and it provides tools to work with these structures

In [1]:
#Installing numpy libary
!pip install numpy

In [2]:
#Importing Numpy Libary
import numpy as np     #np= alias name

#### NumPy Array -- 3 types
#### 1D array, 2D array(axis1,axis0) & 3D array(axis1,axis2,axis0)

In [3]:
#Creating NumPy Arrays
a = np.array([1,2,3])                                        #1D array
print(a)
b = np.array([(1,2,3), (4,5,6)])                             #2D array
print(b)
c = np.array([[(1,2,3), (4,5,6)], [(7,8,9), (10,11,12)]])    #3D array
print(c)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [4]:
#Data Types in NumPy
# np.int64       #64bit integer 
# np.float32     #Floating point number
# np.complex     #Complex number represented by 128 floats
# np.bool        #Boolean Type (True & False)
# np.object      #object type(String)
# np.string_     #Fixed length String type
# np.unicode_    #Fixed length unicode type

In [5]:
#Creating Different types of array by using NumPy initial Placeholders

#Create an array of  zeros -- Row & Col=3 & 4
z = np.zeros((3,4))     

#Create an array of ones  
o = np.ones((2,3,4), dtype=np.int64)

#Create an array of evenly spaced values(step value)     --first two are range value, last is the different
d = np.arange(10,25,5)

#Create an array of evenly spaced values(No. of samples) --first value=starting point, Second=End point, Third=No.of samples
l=np.linspace(0,2,9)

#create a constant array  --Row & Col=2, array of=7
cs=np.full((3,3),7)

#Create a 3X3 identity Matrix
e=np.eye(3,3, dtype=np.int64)

#Create an array with random Values
r=np.random.random((2,3))
r

#Create an empty array
em=np.empty((3,2))

#Note:Run this whole cell, then in below cell type the array's variable to see output

In [6]:
#Inspecting Array using NumPy Attributes
e.shape          #give array dimensions
len(e)           #Length of array
c.ndim           #Number of array dimension
e.size           #Number of array elements
e.dtype          #Data type of array element
a.astype(float)  #Convert an array to dirent type

array([1., 2., 3.])

In [7]:
#Arthematic Operation on array
#addition (+) or np.add()
add = a + b
np.add(a,b)

#Subtraction (-) or np.subtract()
sub = a - b
np.subtract(a,b)

#Division (/) or np.divide()
div = a/b
np.divide(a,b)

#Multiplication (*) or np.multiply()
mul = a*b
np.multiply(a,b)

np.exp(a)     #Exponent (Reminder)
np.sqrt(a)    #Square root
np.sin(a)     #Sines
np.cos(a)     #cosine
np.log(a)     #log
e.dot(cs)     #Dot product

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]], dtype=int64)

In [8]:
#Aggregate Function NumPy
a.sum()           #Array wise sum
a.min()           #Array wise min value
c.max()           #Array wise max value
b.cumsum(axis=1)  #Cumulative sum of the elements
a.mean()          #Mean
np.std(a)         #Standard Deviation

0.816496580927726

In [9]:
#Sorting of array
a.sort()        #sort an array
a.sort(axis=0)  #sort the element of an array's axis

In [10]:
#Subsetting--  index starts at 0


a[2]   
b[1,2] #[row,coln]

6

In [11]:
#Slicing
a[0:2]      #at index 0 & 1
b[0:2,1]    #at rows 0 & 1 in coln 1
b[:1]       #at row 0 
c[1,:,:]    #at row 1 and all coln
a[::-1]     #reverse array

array([3, 2, 1])

In [12]:
#Array Manipulation --Transposing array,

i=np.transpose(b)     #Permute array dimensions
i.T                   #same as np.transpose()
i.reshape(3,2)        #same as np.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [13]:
#Changing array shape
b.ravel()             #flatten the array
b.reshape(3,2)        #where row=3,coln=2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
#Mutating Arrays - Adding and removing Element
np.append(a,add)    #appends two array
np.insert(a,1,5)    #insert item in an array
np.delete(a,[1])    # delete an item at the given index

array([1, 3])

In [15]:
#Combining Arrays
print(a)
print(d)
np.concatenate((a,d))   #combine/concatenate arrays
np.vstack((a,d))        #Stack array vertically
np.r_[cs,e]             #stack array vertically(row-wise)
np.hstack((cs,e))       #stack array horizontally(coln-wise)
np.column_stack((a,d))  #stack array coln wise
np.c_[a,d]              #stack array coln wise

#Note: Run each code of linee individually

[1 2 3]
[10 15 20]


array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

In [16]:
#Splitting Array
np.hsplit(a,3)        #Split the array horizontally at the 3rd index
np.vsplit(c,2)        #Split the array vertically at the 2nd index

[array([[[1, 2, 3],
         [4, 5, 6]]]),
 array([[[ 7,  8,  9],
         [10, 11, 12]]])]